services:
  key-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
    - instance_data:/key-manager/instance
    environment:
      FLASK_ENV: development
volumes:
  instance_data: